DepError: make DependencyNotFound only take one parameter
It can be ambiguous at times which dependency we're looking for, so only
require this error to display the dependency that could not be found.

Signed-off-by: Sean Cross <sean@xobs.io>